run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - ireturn
    - nonamedreturns
    - varnamelen

    - exhaustivestruct
    - scopelint
    - golint
    - varcheck
    - interfacer
    - ifshort
    - deadcode
    - structcheck
    - nosnakecase
    - maligned
